# Generated by Django 3.1 on 2021-04-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ctegory',
            new_name='category',
        ),
    ]
